### ISSUE TITLE
Make this nuget and .net stabdard compiled targets please

### ISSUE THREAD

**Issue by Smurf-IV** [BradSmith1985/NonContig#1]

**Comment by hilkenan** [comment]
I can support this. I could use this if its support .net standard

**Comment by Smurf-IV** [comment]
Once you switch to the new `csproj` format, then you can set build targets and the nuget will also now what to use.
BTW I have a local copy of this project that has the `netstandard2.1` working (Not the unit Tests tho) and a fix for when the `ReadBytes` goes over the end of the buffer (It is supposed to return -1 according to `MemoryStream`!)

**Comment by hilkenan** [comment]
Thanks a lot. Could you send me this Project pls? I need it as MemoryStream replacment.

**Comment by hilkenan** [comment]
I got an error together with sharpcompress. Could your local copy with this fix solve my problem?

System.AggregateException: One or more errors occurred. (Unable to read beyond the end of the stream.)
System.IO<http://system.io/>.EndOfStreamException: Unable to read beyond the end of the stream.
at System.IO<http://system.io/>.BinaryReader.InternalRead(Int32 numBytes)
at System.IO<http://system.io/>.BinaryReader.ReadUInt32()
at SharpCompress.Common.Zip<http://sharpcompress.common.zip/>.SeekableZipHeaderFactory.SeekBackToHeader(Stream stream, BinaryReader reader, UInt32 headerSignature)

**Comment by Smurf-IV** [comment]
Try this:
[NonContig.zip](https://github.com/BradSmith1985/NonContig/files/4936103/NonContig.zip)

**Comment by BradSmith1985** [comment]
Thanks for the suggestion, i've migrated the project file to the SDK format and am now targeting net461, netcoreapp3.1 and netstandard2.1.

Also fixed the issue relating to `NcByteStream.ReadByte` not returning -1 if the position was past the end of the stream.

**Comment by hilkenan** [comment]
I have still this Issus:

System.AggregateException: One or more errors occurred. (Unable to read beyond the end of the stream.)

---> System.IO<http://system.io/>.EndOfStreamException: Unable to read beyond the end of the stream.

at System.IO<http://system.io/>.BinaryReader.InternalRead(Int32 numBytes)

at System.IO<http://system.io/>.BinaryReader.ReadUInt32()

at SharpCompress.Common.Zip<http://sharpcompress.common.zip/>.SeekableZipHeaderFactory.SeekBackToHeader(Stream stream, BinaryReader reader, UInt32 headerSignature)

**Comment by BradSmith1985** [comment]
@hilkenan Please post a minimal, reproducible example that demonstrates the issue you're having.

**Comment by hilkenan** [comment]
using NonContig;

using SharpCompress.Archives.Zip<http://sharpcompress.archives.zip/>;

using System.IO<http://system.io/>;





var contigStream = new NcByteStream();

var file = File.OpenRead("d:\\data_testzip100mb.zip");

file.CopyTo(contigStream);

contigStream.Position = 0;

var archive = ZipArchive.Open<http://ziparchive.open/>(contigStream);

var count = archive.Entries.Count;

The same with the MemoryStream works. Seams here the Read Implementation is the Problem. I think same as for ReadBytes.

Regards
________________________________

**Comment by BradSmith1985** [comment]
@hilkenan Thanks, I was able to reproduce the issue. Check the latest commit, fixed an issue in the `NcByteStream.Seek` method.

**Comment by hilkenan** [comment]
Thx that works. Great!!
________________________________

**Comment by hilkenan** [comment]
I try to load a 1.6gb file. Is it normal thats incredible slow?
________________________________

**Comment by BradSmith1985** [comment]
That is part of the trade-off between performance and memory efficiency. If you haven't read my original article (https://www.brad-smith.info/blog/archives/954) yet, I strongly recommend checking it out - especially the section about performance. For a file of that size, you may want to increase the block size.

I have to question why you need all 1.6gb to be loaded into memory at the same time, though. When dealing with very large files like that, it is better to read the data directly from disk, using a small buffer if you need better performance. Read only what you need, process it and then move onto the next block of data from the file, and so on.
